# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

posts = Post.create(title: 'Post one', body: 'This is post one')
posts = Post.create(title: 'Post two', body: 'This is post two')
posts = Post.create(title: 'Post three', body: 'This is post three')
posts = Post.create(title: 'TOPIC 1 : Write about a person you love or admire', body: 'My mother is a person I admire most. She devoted a lot of time and energy to the upbringing of my two brothers and I. Despite working hard, she always made time to teach us many useful things which are necessary and important in our later lives. Moreover, she is a good role model for me to follow. She always tries to get on well with people who live next door and help everyone when they are in difficulties, so most of them respect and love her. I admire and look up to my mother because she not only brings me up well but also stands by me and gives some help if necessary. For example, when I encounter some difficulties, she will give me some precious advice to help me solve those problems. She has a major influence on me and I hope that I will inherit some of her traits.')
posts = Post.create(title: 'TOPIC 2 : Write about the kind of book you like best', body: 'I am usually in habit of reading books. Addition to books that offer me much useful information,I also like comic book. I am in fond of it for some following reasonsTo begin with, Comic books bring me a great deal of relaxation. One of them is Doremon story, which tells many funny short stories about 2 main characters, Doremon and Nobita,Who are close friends. The author of that comic creats so many amusing situations among characters that I can’t help laughing. It’s actually a hard-to-put-down book. It attracts not only children but also adults as me.Another good point of it I want to mention about is creative imagination. I mean children need to have imaginative mindset, which helps them be more active in life.By and large, comic book is worth reading after hard work. It is nice for everyone.')
posts = Post.create(title: 'TOPIC 3 : What kind of job would you like to do after you finish your education?', body: 'Marketing seems to be the kind of career I would like to choose after i leave from university. I like this work in view of some following reasons.First of all, marketing position is well-paid job. The more you help your company sell more products, the higher your salary is. Of course, you need to have effective stragedies to attract customers.Secondly, Working as a marketer gives me many opportunities of improving my persuding skill and ability to converting idea into words. There is no denial that this kind of job requires different skills , but if you meet these requirements, you will be more and more professional.On the whole, it is simply my hobby. Needless to say ”you will do something best when you like it”.')

users = User.create(email: 'admin@gmail.com' , password: 'ad1234')
users = User.create(email: 'thanh@gmail.com' , password: '456789')